apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-service
  namespace: customer
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: customer-service
        namespace: customer
    spec:
      containers:
      - name: customer-service
        image: badalacr.azurecr.io/customer-service:v1
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: customer
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: customer-service