apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-order-service
  namespace: customer
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: customer-order-service
        namespace: customer
    spec:
      containers:
      - name: customer-order-service
        image: badalacr.azurecr.io/customer-order-service:v1
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: customer-order-service
  namespace: customer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: customer-order-service