apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: customer
spec:
  type: ClusterIP
  ports:
  - name: tcp-80
    port: 80
    targetPort: cust-web
    protocol: TCP
  - name: tcp-443
    port: 443
    targetPort: cust-sec-web
    protocol: TCP
  selector:
    app: customer-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-service
  namespace: customer
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: customer-service
        namespace: customer
    spec:
      containers:
      - name: customer-service
        image: badalacr.azurecr.io/customer-service:v1
        ports:
        - name: cust-web
          containerPort: 80
          protocol: TCP
        - name: cust-sec-web
          containerPort: 443
          protocol:  TCP
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

