apiVersion: v1
kind: Service
metadata:
  name: new-product-service
  namespace: product
spec:
  type: LoadBalancer
  ports:
  - name: tcp-80
    port: 80
    targetPort: http
    protocol: TCP
  - name: tcp-443
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: new-product-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: new-product-service
  namespace: product
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: new-product-service
        namespace: product
    spec:
      containers:
      - name: new-product-service
        image: badalacr.azurecr.io/new-product-service:v1
        imagePullPolicy: Always
        env:
          - name: SECRET_DBNAME
            valueFrom:
              secretKeyRef:
                name: prod-osba-sql-secret
                key: database
          - name: SECRET_ENCRYPT
            valueFrom:
              secretKeyRef:
                name: prod-osba-sql-secret
                key: encrypt
          - name: SECRET_HOST
            valueFrom:
              secretKeyRef:
                name: prod-osba-sql-secret
                key: host
          - name: SECRET_PORT
            valueFrom:
              secretKeyRef:
                name: prod-osba-sql-secret
                key: port
          - name: SECRET_URI
            valueFrom:
              secretKeyRef:
                name: prod-osba-sql-secret
                key: uri
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: prod-osba-sql-secret
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-osba-sql-secret
                key: password
        volumeMounts:
        - name: sqlsecrets
          mountPath: "/etc/sqlsecrets"
          readOnly: true
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol:  TCP
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
      volumes:
      - name: sqlsecrets
        secret:
          secretName: prod-osba-sql-secret
          items:
          - key: database
            path: db/database
          - key: host
            path: db/host
          - key: port
            path: db/port
          - key: uri
            path: db/uri
          - key: username
            path: db/username
          - key: password
            path: db/password
          - key: encrypt
            path: db/encrypt
