apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
 name: prodpodidentitybinding
spec:
 AzureIdentity: k8s-kv-identity
 Selector: prodpodidbinding
---
apiVersion: v1
kind: Service
metadata:
  name: osba-product-service
  namespace: product
spec:
  type: ClusterIP
  ports:
  - name: tcp-80
    port: 80
    targetPort: prod-web
    protocol: TCP
  - name: tcp-443
    port: 443
    targetPort: prod-secure-web
    protocol: TCP
  selector:
    app: osba-product-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: osba-product-service
  namespace: product
  labels:
    app: osba-product-service
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: osba-product-service
        namespace: product
        aadpodbinding: prodpodidbinding
    spec:
      containers:
      - name: osba-product-service
        image: badalacr.azurecr.io/osba-product-service:v1
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /kvmnt
            name: prodkeys
            readOnly: true
        volumes:
        - name: prodkeys
          flexVolume:
            driver: "azure/kv"
            options:
              usepodidentity: "true"         # [OPTIONAL] if not provided, will default to "false"
              keyvaultname: "aks-sp-key-secret-vault"               # the name of the KeyVault
              keyvaultobjectnames: "sqlpwd;sqluser;az-aks-arm-sp-secret"        # list of KeyVault object names (semi-colon separated)
              keyvaultobjecttypes: "secret;secret;secret"    # list of KeyVault object types: secret, key or cert (semi-colon separated)
              keyvaultobjectversions: "237851d935e24ac8b63abb1b41a01854;d9acf08f9a1243dbae8f9e85e5cbf573;3fd8702bf4114c5a805f62e914eac823"     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
              resourcegroup: "rg-secrets"              # the resource group of the KeyVault
              subscriptionid: "4dfeb08c-7e41-40af-a9fa-fabcac401c2d"             # the subscription ID of the KeyVault
              tenantid: "b25fcb44-9c49-413c-9fdc-b59b39447b84"                   # the tenant ID of the KeyVault
        ports:
        - name: prod-web
          containerPort: 80
          protocol: TCP
        - name: prod-secure-web
          containerPort: 443
          protocol:  TCP
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
