apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: product-service
  namespace: product
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: product-service
        namespace: product
    spec:
      containers:
      - name: product-service
        image: badalacr.azurecr.io/product-service:v1
        ports:
        - name: prod-web
          containerPort: 80
          protocol: TCP
        - name: prod-secure-web
          containerPort: 443
          protocol:  TCP
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product
spec:
  type: LoadBalancer
  loadBalancerIP: 104.46.96.249
  ports:
  - name: tcp-80
    port: 80
    targetPort: prod-web
    protocol: TCP
  - name: tcp-443
    port: 443
    targetPort: prod-secure-web
    protocol: TCP
  selector:
    app: product-service