kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: np-new-product-service-allow-appgw
  namespace: product
spec:
  podSelector:
    matchLabels:
      app: new-product-service-appgw
  ingress:
  - ports:
    - port: 80
    - port: 443
  - from: 
    - ipBlock:
        cidr: xxx.xxx.xxx.xxx/32 #App GW IP