apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: k8s-kv-identity
spec:
 type: 0
 ResourceID: /subscriptions/4dfeb08c-7e41-40af-a9fa-fabcac401c2d/resourcegroups/rg-secrets/providers/Microsoft.ManagedIdentity/userAssignedIdentities/k8s-kv-identity
 ClientID: e9388487-fafb-4ea2-8a18-e993c279bfd3