apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-flex-kv-podid
    aadpodidbinding: prodpod
  name: nginx-flex-kv-podid
spec:
  containers:
  - name: nginx-flex-kv-podid
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"         # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "aks-sp-key-secret-vault"               # the name of the KeyVault
        keyvaultobjectnames: "dbhost;dbport;dbname;username;password;encrypt"        # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: "secret;secret;secret;secret;secret;secret"    # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: "47b45e005d604f67ae759ceec89ddcf6;3c6c9c312de545328d5ccf0009693bee;500f70812a274a4180b1477d3208bd6a;8a11530b74094c918be7f349e8f5e5f5;fa52a58c52e54d6d847c09e5b5ab91b6;9c827b69280347d0aa2cc491d72e1679"     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "rg-secrets"              # the resource group of the KeyVault
        subscriptionid: "4dfeb08c-7e41-40af-a9fa-fabcac401c2d"             # the subscription ID of the KeyVault
        tenantid: "b25fcb44-9c49-413c-9fdc-b59b39447b84"                   # the tenant ID of the KeyVault
