kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: product
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - ipBlock:
        # cidr: 10.0.0.0/16
        cidr: 40.70.128.221
    - podSelector: {}