kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-allow-external
  namespace: product
spec:
  podSelector:
    matchLabels:
      app: new-product-service-kvflex
  ingress:
  - ports:
    - port: 80
      name: web
    - port: 443
      name: secureweb    
  - from: []